"""Boundary and shared contracts for Product Packs."""

from pmqa.product_pack.bridge_protocol import (
    BRIDGE_PROTOCOL_VERSION,
    MAX_BRIDGE_ACTION_COUNT,
    ProductPackBridgeFailureCode,
    ProductPackBridgeOperation,
    ProductPackBridgeProtocolError,
    ProductPackBridgeProtocolErrorCode,
    ProductPackBridgeRequest,
    ProductPackBridgeResponse,
    ProductPackBridgeStatus,
    bridge_protocol_v1_schema,
    validate_product_pack_bridge_response,
)
from pmqa.product_pack.bridge_runner import (
    DEFAULT_BRIDGE_TIMEOUT_SECONDS,
    DEFAULT_MAX_REQUEST_BYTES,
    DEFAULT_MAX_STDERR_BYTES,
    DEFAULT_MAX_STDOUT_BYTES,
    ProductPackBridgeExecutionError,
    ProductPackBridgeExecutionErrorCode,
    ProductPackBridgeProcessConfig,
    run_product_pack_bridge,
)
from pmqa.product_pack.manifest import (
    ProductPackCapability,
    ProductPackManifest,
    ProductPackManifestValidationError,
)
from pmqa.product_pack.loader import (
    LoadedProductPack,
    PRODUCT_PACK_ENTRY_POINT_GROUP,
    ProductPackLoadError,
    ProductPackLoadFailureCode,
    ProductPackLoadRequest,
    load_product_pack_manifest,
)
from pmqa.product_pack.scaffold import (
    PRODUCT_PACK_SCAFFOLD_VERSION,
    ProductPackScaffoldError,
    ProductPackScaffoldErrorCode,
    ProductPackScaffoldRequest,
    ProductPackScaffoldResult,
    ProductPackSourceConformanceErrorCode,
    ProductPackSourceConformanceResult,
    scaffold_product_pack,
    validate_product_pack_source,
)

__all__ = [
    "BRIDGE_PROTOCOL_VERSION",
    "MAX_BRIDGE_ACTION_COUNT",
    "DEFAULT_BRIDGE_TIMEOUT_SECONDS",
    "DEFAULT_MAX_REQUEST_BYTES",
    "DEFAULT_MAX_STDERR_BYTES",
    "DEFAULT_MAX_STDOUT_BYTES",
    "ProductPackCapability",
    "ProductPackManifest",
    "ProductPackManifestValidationError",
    "LoadedProductPack",
    "PRODUCT_PACK_ENTRY_POINT_GROUP",
    "ProductPackLoadError",
    "ProductPackLoadFailureCode",
    "ProductPackLoadRequest",
    "load_product_pack_manifest",
    "ProductPackBridgeFailureCode",
    "ProductPackBridgeOperation",
    "ProductPackBridgeProtocolError",
    "ProductPackBridgeProtocolErrorCode",
    "ProductPackBridgeRequest",
    "ProductPackBridgeResponse",
    "ProductPackBridgeStatus",
    "bridge_protocol_v1_schema",
    "validate_product_pack_bridge_response",
    "ProductPackBridgeExecutionError",
    "ProductPackBridgeExecutionErrorCode",
    "ProductPackBridgeProcessConfig",
    "run_product_pack_bridge",
    "PRODUCT_PACK_SCAFFOLD_VERSION",
    "ProductPackScaffoldError",
    "ProductPackScaffoldErrorCode",
    "ProductPackScaffoldRequest",
    "ProductPackScaffoldResult",
    "ProductPackSourceConformanceErrorCode",
    "ProductPackSourceConformanceResult",
    "scaffold_product_pack",
    "validate_product_pack_source",
]
