"""Provider-neutral local conversation contracts and persistence."""

from pmqa.conversation.contracts import (
    CONVERSATION_SCHEMA_VERSION,
    DEFAULT_CONVERSATION_LIST_LIMIT,
    MAX_CONVERSATION_LIST_LIMIT,
    MAX_CONVERSATION_MESSAGE_LENGTH,
    MAX_CONVERSATION_REVISION,
    MAX_CONVERSATION_TURNS,
    ConversationContractValidationError,
    ConversationRetentionPolicy,
    ConversationSensitiveTextError,
    ConversationSession,
    ConversationSessionStatus,
    ConversationTurn,
    ConversationTurnErrorCode,
    ConversationTurnStatus,
    conversation_expiration,
    conversation_turn_error_message,
)
from pmqa.conversation.repository import (
    CONVERSATION_REPOSITORY_SCHEMA_NAME,
    CONVERSATION_REPOSITORY_SCHEMA_VERSION,
    MAX_CONVERSATION_RECORD_BYTES,
    ConversationRepository,
    ConversationRepositoryError,
    ConversationRepositoryErrorCode,
    InMemoryConversationRepository,
    SQLiteConversationRepository,
)
from pmqa.conversation.service import (
    DEFAULT_CONVERSATION_RETENTION,
    ConversationApplicationError,
    ConversationApplicationErrorCode,
    ConversationApplicationService,
)

__all__ = [
    "CONVERSATION_REPOSITORY_SCHEMA_NAME",
    "CONVERSATION_REPOSITORY_SCHEMA_VERSION",
    "CONVERSATION_SCHEMA_VERSION",
    "DEFAULT_CONVERSATION_LIST_LIMIT",
    "DEFAULT_CONVERSATION_RETENTION",
    "MAX_CONVERSATION_LIST_LIMIT",
    "MAX_CONVERSATION_MESSAGE_LENGTH",
    "MAX_CONVERSATION_RECORD_BYTES",
    "MAX_CONVERSATION_REVISION",
    "MAX_CONVERSATION_TURNS",
    "ConversationApplicationError",
    "ConversationApplicationErrorCode",
    "ConversationApplicationService",
    "ConversationContractValidationError",
    "ConversationRepository",
    "ConversationRepositoryError",
    "ConversationRepositoryErrorCode",
    "ConversationRetentionPolicy",
    "ConversationSensitiveTextError",
    "ConversationSession",
    "ConversationSessionStatus",
    "ConversationTurn",
    "ConversationTurnErrorCode",
    "ConversationTurnStatus",
    "InMemoryConversationRepository",
    "SQLiteConversationRepository",
    "conversation_expiration",
    "conversation_turn_error_message",
]
